name: "Continues Integration Workflow"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  linting:
    name: "Run Linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --diff --color"
          src: "./users"

  test:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "Checkout to the project source"

      - name: "Set up Python Environment"
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        run: |
          python pip install -r requirements.txt

      - name: "Execute Tests"
        run: |
          python manage.py test
